config/routes.rb
Manalist::Application.routes.draw do
  resources :deck_matchups

  resources :card_expansions

  resources :deck_sides

  resources :side_cards

  resources :deck_cards

  resources :player_relationships

  resources :side_boards

  resources :decks

  resources :expansions

  resources :cards

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/expansion.rb
class Expansion < ActiveRecord::Base

  has_many :card_expansions, :dependent => :destroy
  has_many :cards, :through => :card_expansions

end

app/controllers/expansions_controller.rb
class ExpansionsController < ApplicationController
  before_action :set_expansion, only: [:show, :edit, :update, :destroy]

  # GET /expansions
  # GET /expansions.json
  def index
    @expansions = Expansion.all
  end

  # GET /expansions/1
  # GET /expansions/1.json
  def show
  end

  # GET /expansions/new
  def new
    @expansion = Expansion.new
  end

  # GET /expansions/1/edit
  def edit
  end

  # POST /expansions
  # POST /expansions.json
  def create
    @expansion = Expansion.new(expansion_params)

    respond_to do |format|
      if @expansion.save
        format.html { redirect_to @expansion, notice: 'Expansion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expansion }
      else
        format.html { render action: 'new' }
        format.json { render json: @expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expansions/1
  # PATCH/PUT /expansions/1.json
  def update
    respond_to do |format|
      if @expansion.update(expansion_params)
        format.html { redirect_to @expansion, notice: 'Expansion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expansions/1
  # DELETE /expansions/1.json
  def destroy
    @expansion.destroy
    respond_to do |format|
      format.html { redirect_to expansions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expansion
      @expansion = Expansion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expansion_params
      params.require(:expansion).permit(:set_code, :name, :symbol, :size, :common_cards_num, :uncommon_cards_num, :rare_cards_num, :mythic_cards_num, :other_cards_num)
    end
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/views/expansions/_form.html.erb
<%= form_for(@expansion) do |f| %>
  <% if @expansion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expansion.errors.count, "error") %> prohibited this expansion from being saved:</h2>

      <ul>
      <% @expansion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :set_code %><br>
    <%= f.text_field :set_code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :common_cards_num %><br>
    <%= f.text_field :common_cards_num %>
  </div>
  <div class="field">
    <%= f.label :uncommon_cards_num %><br>
    <%= f.text_field :uncommon_cards_num %>
  </div>
  <div class="field">
    <%= f.label :rare_cards_num %><br>
    <%= f.text_field :rare_cards_num %>
  </div>
  <div class="field">
    <%= f.label :mythic_cards_num %><br>
    <%= f.text_field :mythic_cards_num %>
  </div>
  <div class="field">
    <%= f.label :other_cards_num %><br>
    <%= f.text_field :other_cards_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expansions/edit.html.erb
<h1>Editing expansion</h1>

<%= render 'form' %>

<%= link_to 'Show', @expansion %> |
<%= link_to 'Back', expansions_path %>

app/views/expansions/index.html.erb
<h1>Expansions <small>Admin</small></h1>

<%= link_to 'New Expansion', new_expansion_path %>

<%= form_tag expansions_path, method: 'get', html: {role: "form"} do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
    <%= link_to "All", expansions_path, {class: "btn btn-sm btn-link"} %>
  </p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Set code</th>
      <th>Name</th>
      <th>Symbol</th>
      <th>Size</th>
      <th>Common cards num</th>
      <th>Uncommon cards num</th>
      <th>Rare cards num</th>
      <th>Mythic cards num</th>
      <th>Other cards num</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expansions.each do |expansion| %>
      <tr>
        <td><%= expansion.set_code %></td>
        <td><%= expansion.name %></td>
        <td><%= expansion.symbol %></td>
        <td><%= expansion.size %></td>
        <td><%= expansion.common_cards_num %></td>
        <td><%= expansion.uncommon_cards_num %></td>
        <td><%= expansion.rare_cards_num %></td>
        <td><%= expansion.mythic_cards_num %></td>
        <td><%= expansion.other_cards_num %></td>
        <td><%= link_to 'Show', expansion %></td>
        <td><%= link_to 'Edit', edit_expansion_path(expansion) %></td>
        <td><%= link_to 'Destroy', expansion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Back to Admin", admin_root_path %></p>

app/views/expansions/new.html.erb
<h1>New expansion</h1>

<%= render 'form' %>

<%= link_to 'Back', expansions_path %>

app/views/expansions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Set code:</strong>
  <%= @expansion.set_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @expansion.name %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @expansion.symbol %>
</p>

<p>
  <strong>Size:</strong>
  <%= @expansion.size %>
</p>

<p>
  <strong>Common cards num:</strong>
  <%= @expansion.common_cards_num %>
</p>

<p>
  <strong>Uncommon cards num:</strong>
  <%= @expansion.uncommon_cards_num %>
</p>

<p>
  <strong>Rare cards num:</strong>
  <%= @expansion.rare_cards_num %>
</p>

<p>
  <strong>Mythic cards num:</strong>
  <%= @expansion.mythic_cards_num %>
</p>

<p>
  <strong>Other cards num:</strong>
  <%= @expansion.other_cards_num %>
</p>

<%= link_to 'Edit', edit_expansion_path(@expansion) %> |
<%= link_to 'Back', expansions_path %>