config/routes.rb
Manalist::Application.routes.draw do
  resources :deck_matchups

  resources :card_expansions

  resources :deck_sides

  resources :side_cards

  resources :deck_cards

  resources :player_relationships

  resources :side_boards

  resources :decks

  resources :expansions

  resources :cards

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/card_expansion.rb
require 'octopus'
require 'composite_primary_keys'

class CardExpansion < ActiveRecord::Base
    self.primary_keys = [:card_id, :expansion_id]



   belongs_to :card, :foreign_key => [:card_id, :expansion_id]
   belongs_to :expansion
end

app/controllers/card_expansions_controller.rb
class CardExpansionsController < ApplicationController
  before_action :set_card_expansion, only: [:show, :edit, :update, :destroy]

  # GET /card_expansions
  # GET /card_expansions.json
  def index
    @card_expansions = CardExpansion.all
  end

  # GET /card_expansions/1
  # GET /card_expansions/1.json
  def show
  end

  # GET /card_expansions/new
  def new
    @card_expansion = CardExpansion.new
  end

  # GET /card_expansions/1/edit
  def edit
  end

  # POST /card_expansions
  # POST /card_expansions.json
  def create
    @card_expansion = CardExpansion.new(card_expansion_params)

    respond_to do |format|
      if @card_expansion.save
        format.html { redirect_to @card_expansion, notice: 'Card expansion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card_expansion }
      else
        format.html { render action: 'new' }
        format.json { render json: @card_expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_expansions/1
  # PATCH/PUT /card_expansions/1.json
  def update
    respond_to do |format|
      if @card_expansion.update(card_expansion_params)
        format.html { redirect_to @card_expansion, notice: 'Card expansion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card_expansion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_expansions/1
  # DELETE /card_expansions/1.json
  def destroy
    @card_expansion.destroy
    respond_to do |format|
      format.html { redirect_to card_expansions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_expansion
      @card_expansion = CardExpansion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_expansion_params
      params.require(:card_expansion).permit( :rarity, :card_num, :image)
    end
end

app/helpers/card_expansions_helper.rb
module CardExpansionsHelper
end

app/views/card_expansions/_form.html.erb
<%= form_for(@card_expansion) do |f| %>
  <% if @card_expansion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card_expansion.errors.count, "error") %> prohibited this card_expansion from being saved:</h2>

      <ul>
      <% @card_expansion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :set_code %><br>
    <%= f.text_field :set_code %>
  </div>
  <div class="field">
    <%= f.label :card_name %><br>
    <%= f.text_field :card_name %>
  </div>
  <div class="field">
    <%= f.label :rarity %><br>
    <%= f.text_field :rarity %>
  </div>
  <div class="field">
    <%= f.label :card_num %><br>
    <%= f.text_field :card_num %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/card_expansions/edit.html.erb
<h1>Editing card_expansion</h1>

<%= render 'form' %>

<%= link_to 'Show', @card_expansion %> |
<%= link_to 'Back', card_expansions_path %>

app/views/card_expansions/index.html.erb
<h1>Listing card_expansions</h1>

<table>
  <thead>
    <tr>
      <th>Expansion ID</th>
      <th>Card ID</th>
      <th>Rarity</th>
      <th>Card num</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @card_expansions.each do |card_expansion| %>
      <tr>
        <td><%= card_expansion.expansion_id %></td>
        <td><%= card_expansion.card_id %></td>
        <td><%= card_expansion.rarity %></td>
        <td><%= card_expansion.card_num %></td>
        <td><%= card_expansion.image %></td>
        <td><%= link_to 'Show', card_expansion %></td>
        <td><%= link_to 'Edit', edit_card_expansion_path(card_expansion) %></td>
        <td><%= link_to 'Destroy', card_expansion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card expansion', new_card_expansion_path %>

app/views/card_expansions/new.html.erb
<h1>New card_expansion</h1>

<%= render 'form' %>

<%= link_to 'Back', card_expansions_path %>

app/views/card_expansions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Set code:</strong>
  <%= @card_expansion.set_code %>
</p>

<p>
  <strong>Card name:</strong>
  <%= @card_expansion.card_name %>
</p>

<p>
  <strong>Rarity:</strong>
  <%= @card_expansion.rarity %>
</p>

<p>
  <strong>Card num:</strong>
  <%= @card_expansion.card_num %>
</p>

<p>
  <strong>Image:</strong>
  <%= @card_expansion.image %>
</p>

<%= link_to 'Edit', edit_card_expansion_path(@card_expansion) %> |
<%= link_to 'Back', card_expansions_path %>