config/routes.rb
Manalist::Application.routes.draw do
  resources :deck_matchups

  resources :card_expansions

  resources :deck_sides

  resources :side_cards

  resources :deck_cards

  resources :player_relationships

  resources :side_boards

  resources :decks

  resources :expansions

  resources :cards

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/player_relationship.rb
class PlayerRelationship < ActiveRecord::Base
end

app/controllers/player_relationships_controller.rb
class PlayerRelationshipsController < ApplicationController
  before_action :set_player_relationship, only: [:show, :edit, :update, :destroy]

  # GET /player_relationships
  # GET /player_relationships.json
  def index
    @player_relationships = PlayerRelationship.all
  end

  # GET /player_relationships/1
  # GET /player_relationships/1.json
  def show
  end

  # GET /player_relationships/new
  def new
    @player_relationship = PlayerRelationship.new
  end

  # GET /player_relationships/1/edit
  def edit
  end

  # POST /player_relationships
  # POST /player_relationships.json
  def create
    @player_relationship = PlayerRelationship.new(player_relationship_params)

    respond_to do |format|
      if @player_relationship.save
        format.html { redirect_to @player_relationship, notice: 'Player relationship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player_relationship }
      else
        format.html { render action: 'new' }
        format.json { render json: @player_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_relationships/1
  # PATCH/PUT /player_relationships/1.json
  def update
    respond_to do |format|
      if @player_relationship.update(player_relationship_params)
        format.html { redirect_to @player_relationship, notice: 'Player relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player_relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_relationships/1
  # DELETE /player_relationships/1.json
  def destroy
    @player_relationship.destroy
    respond_to do |format|
      format.html { redirect_to player_relationships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_relationship
      @player_relationship = PlayerRelationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_relationship_params
      params.require(:player_relationship).permit(:username_1, :username_2, :relationship_type)
    end
end

app/helpers/player_relationships_helper.rb
module PlayerRelationshipsHelper
end

app/views/player_relationships/_form.html.erb
<%= form_for(@player_relationship) do |f| %>
  <% if @player_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_relationship.errors.count, "error") %> prohibited this player_relationship from being saved:</h2>

      <ul>
      <% @player_relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username_1 %><br>
    <%= f.text_field :username_1 %>
  </div>
  <div class="field">
    <%= f.label :username_2 %><br>
    <%= f.text_field :username_2 %>
  </div>
  <div class="field">
    <%= f.label :relationship_type %><br>
    <%= f.text_field :relationship_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_relationships/edit.html.erb
<h1>Editing player_relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_relationship %> |
<%= link_to 'Back', player_relationships_path %>

app/views/player_relationships/index.html.erb
<h1>Listing player_relationships</h1>

<table>
  <thead>
    <tr>
      <th>Username 1</th>
      <th>Username 2</th>
      <th>Relationship type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @player_relationships.each do |player_relationship| %>
      <tr>
        <td><%= player_relationship.username_1 %></td>
        <td><%= player_relationship.username_2 %></td>
        <td><%= player_relationship.relationship_type %></td>
        <td><%= link_to 'Show', player_relationship %></td>
        <td><%= link_to 'Edit', edit_player_relationship_path(player_relationship) %></td>
        <td><%= link_to 'Destroy', player_relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player relationship', new_player_relationship_path %>

app/views/player_relationships/new.html.erb
<h1>New player_relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', player_relationships_path %>

app/views/player_relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username 1:</strong>
  <%= @player_relationship.username_1 %>
</p>

<p>
  <strong>Username 2:</strong>
  <%= @player_relationship.username_2 %>
</p>

<p>
  <strong>Relationship type:</strong>
  <%= @player_relationship.relationship_type %>
</p>

<%= link_to 'Edit', edit_player_relationship_path(@player_relationship) %> |
<%= link_to 'Back', player_relationships_path %>