config/routes.rb
Manalist::Application.routes.draw do
  resources :deck_matchups

  resources :card_expansions

  resources :deck_sides

  resources :side_cards

  resources :deck_cards

  resources :player_relationships

  resources :side_boards

  resources :decks

  resources :expansions

  resources :cards

  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end
  
end

app/models/card.rb
class Card < ActiveRecord::Base

 has_many :card_expansions, :class_name => 'CardExpansion', :foreign_key => [:card_id, :expansion_id], :dependent => :destroy
    
   has_one :expansion, :through => :card_expansions
   accepts_nested_attributes_for :card_expansions


    has_and_belongs_to_many :CardExpansions

end

app/models/card_expansion.rb
require 'octopus'
require 'composite_primary_keys'

class CardExpansion < ActiveRecord::Base
    self.primary_keys = [:card_id, :expansion_id]



   belongs_to :card, :foreign_key => [:card_id, :expansion_id]
   belongs_to :expansion
end

app/models/deck.rb
class Deck < ActiveRecord::Base
end

app/models/deck_card.rb
class DeckCard < ActiveRecord::Base
end

app/models/deck_matchup.rb
class DeckMatchup < ActiveRecord::Base
end

app/models/deck_side.rb
class DeckSide < ActiveRecord::Base
end

app/models/expansion.rb
class Expansion < ActiveRecord::Base

  has_many :card_expansions, :dependent => :destroy
  has_many :cards, :through => :card_expansions

end

app/models/player_relationship.rb
class PlayerRelationship < ActiveRecord::Base
end

app/models/side_board.rb
class SideBoard < ActiveRecord::Base
end

app/models/side_card.rb
class SideCard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Pagination
  paginates_per 100
  
  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..10 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
   
    
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params[:id])
    @card.card_expansions.build 


    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end 
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:cardname, :manacost, :color, :power, :toughness, :loyalty_counter, :card_type, :description, card_expansion_attributes: [ :rarity, :cardnum, :image])
     
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deck }
      else
        format.html { render action: 'new' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:deck_id, :username, :name, :format, :type, :colors, :rating, :creation_date, :last_update)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
  end
  
  def inside
  end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Manalist"      
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/deck_cards_helper.rb
module DeckCardsHelper
end

app/helpers/deck_matchups_helper.rb
module DeckMatchupsHelper
end

app/helpers/deck_sides_helper.rb
module DeckSidesHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/helpers/side_boards_helper.rb
module SideBoardsHelper
end

app/helpers/side_cards_helper.rb
module SideCardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cardname %><br>
    <%= f.text_field :cardname %>
  </div>
  <div class="field">
    <%= f.label :manacost %><br>
    <%= f.text_field :manacost %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </div>
  <div class="field">
    <%= f.label :toughness %><br>
    <%= f.text_field :toughness %>
  </div>
  <div class="field">
    <%= f.label :loyalty_counter %><br>
    <%= f.text_field :loyalty_counter %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>
   <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  
  <%= fields_for :card_expansions   do |fa| %>
  <%= fa.hidden_field :card_id, :value => @card.id %>
  <%= fa.hidden_field :expansion_id, :value => '1'%>
  <div class="field">
    <%= fa.label :rarity %><br>
    <%= fa.text_field :rarity %>
  </div>
  <div class="field">
    <%= fa.label :card_num %><br>
    <%= fa.text_field :card_num %>
  </div>
  <div class="field">
    <%= fa.label :image %><br>
    <%= fa.text_field :image %>
  </div>
  
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Cards <small>Admin</small></h1>

<%= link_to 'New Card', new_card_path %>

<%= form_tag cards_path, method: 'get', html: {role: "form"} do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
    <%= link_to "All", cards_path, {class: "btn btn-sm btn-link"} %>
  </p>
<% end %>

<table class="table table-striped">
  <tr>
     <th>Cardname</th>
      <th>Manacost</th>
      <th>Color</th>
      <th>Power</th>
      <th>Toughness</th>
      <th>Loyalty counter</th>
      <th>Card type</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.cardname %></td>
        <td><%= card.manacost %></td>
        <td><%= card.color %></td>
        <td><%= card.power %></td>
        <td><%= card.toughness %></td>
        <td><%= card.loyalty_counter %></td>
        <td><%= card.card_type %></td>
        <td><%= card.description %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  
  <% end %>
  
</table>

<p><%= link_to "Back to Admin", admin_root_path %></p>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cardname:</strong>
  <%= @card.cardname %>
</p>

<p>
  <strong>Manacost:</strong>
  <%= @card.manacost %>
</p>

<p>
  <strong>Color:</strong>
  <%= @card.color %>
</p>

<p>
  <strong>Power:</strong>
  <%= @card.power %>
</p>

<p>
  <strong>Toughness:</strong>
  <%= @card.toughness %>
</p>

<p>
  <strong>Loyalty counter:</strong>
  <%= @card.loyalty_counter %>
</p>

<p>
  <strong>Card type:</strong>
  <%= @card.card_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deck_id %><br>
    <%= f.text_field :deck_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :colors %><br>
    <%= f.text_field :colors %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :creation_date %><br>
    <%= f.date_select :creation_date %>
  </div>
  <div class="field">
    <%= f.label :last_update %><br>
    <%= f.date_select :last_update %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <thead>
    <tr>
      <th>Deck</th>
      <th>Username</th>
      <th>Name</th>
      <th>Format</th>
      <th>Type</th>
      <th>Colors</th>
      <th>Rating</th>
      <th>Creation date</th>
      <th>Last update</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.deck_id %></td>
        <td><%= deck.username %></td>
        <td><%= deck.name %></td>
        <td><%= deck.format %></td>
        <td><%= deck.type %></td>
        <td><%= deck.colors %></td>
        <td><%= deck.rating %></td>
        <td><%= deck.creation_date %></td>
        <td><%= deck.last_update %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deck:</strong>
  <%= @deck.deck_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @deck.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @deck.name %>
</p>

<p>
  <strong>Format:</strong>
  <%= @deck.format %>
</p>

<p>
  <strong>Type:</strong>
  <%= @deck.type %>
</p>

<p>
  <strong>Colors:</strong>
  <%= @deck.colors %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @deck.rating %>
</p>

<p>
  <strong>Creation date:</strong>
  <%= @deck.creation_date %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @deck.last_update %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>